title : PseudoLab PyTorch guide
author: PseudoLab
logo: 'PseudoLab_logo.png'

# Short description about the book
description: >-
  PyTorch guide for basic of deep-learning

execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  favicon: 'PseudoLab_logo.png'
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/Pseudo-Lab/pytorch-guide
  path_to_book                : "book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

exclude_patterns: [temp/*]